m4a2mp3: cleanup logging/messages output

diff --git a/SCRIPTS/m4a2mp3 b/SCRIPTS/m4a2mp3
--- a/SCRIPTS/m4a2mp3
+++ b/SCRIPTS/m4a2mp3
@@ -6,31 +6,31 @@ set -o errexit
 set -o nounset
 
 if ! command -v faad >/dev/null; then
-  echo "faad executable not found." >&2;
+  echo "[ERROR] faad executable not found." >&2;
   exit 1;
 fi
 if ! command -v lame >/dev/null; then
-  echo "lame executable not found." >&2;
+  echo "[ERROR] lame executable not found." >&2;
   exit 1;
 fi
 if ! command -v id3v2 >/dev/null; then
-  echo "id3v2 executable not found." >&2;
+  echo "[ERROR] id3v2 executable not found." >&2;
   exit 1;
 fi
 
-echo -n "Delete m4a file(s) after conversion?(y/n) "
+echo -n "[Q] Delete m4a file(s) after conversion?(y/n) "
 read -r yn
 case $yn in
   y|yes)
-      echo -e "All right $USER, m4a files will be removed."
+      echo -e "[INFO] m4a files will be removed."
       del=0
       ;;
   *)
-      echo -e "Ok $USER, m4a files will be preserved."
+      echo -e "[INFO] m4a files will be preserved."
       ;;
 esac
 
-echo -e "\nBe patient if you convert lots of file."
+echo -e "[INFO] Be patient if you convert lots of files."
 
 while read -r m4afile; do
 
@@ -48,8 +48,8 @@ while read -r m4afile; do
   PERFORMER=$(faad -i "$m4afile" 2>&1 | grep '^performer: ' | sed 's/^performer: //')
   ALBARTIST=$(faad -i "$m4afile" 2>&1 | grep '^album_artist: ' | sed 's/^album_artist: //')
 
-  echo -en "\n$ARTIST / $ALBUM [$DATE] / $TRACKNUMBER - $TITLE"
-  echo -en "\nConverting *$(basename "$m4afile")* to *$(basename "$mp3file")* ..."
+  echo -en "[INFO] $ARTIST / $ALBUM [$DATE] / $TRACKNUMBER - $TITLE"
+  echo -en "[INFO] Converting *$(basename "$m4afile")* to *$(basename "$mp3file")* ..."
   faad -q -o - "$m4afile" 2>/dev/null | lame -m j -q 0 --vbr-new -V 0 -s 44.1 - "$mp3file" 2>/dev/null
 
   id3v2 -t "$TITLE" -T "${TRACKNUMBER:-0}" -a "$ARTIST" -A "$ALBUM" -y "$DATE" -g "${GENRE:-12}" -c "$COMMENT" --TORY "$DATE" --IPLS "$ALBARTIST" --TCOM "$COMPOSER" --TIT1 "$CONGROUP" --TIT2 "$TITLE" --TOPE "$PERFORMER" --TPE1 "$ARTIST" --TPE2 "$ALBARTIST" --TRCK "$TRACKNUMBER" "$mp3file" 2>/dev/null
@@ -59,5 +59,4 @@ while read -r m4afile; do
   fi
 
 done < <(find . -iname '*.m4a' -or -iname '*.M4A')
-echo -e "\nConversion complete!"
-
+echo -e "[INFO] Conversion complete!"
